name: Deploy to Production (DISABLED - Now using GitHub Pages)

on:
  # Disabled - no longer deploying to server, using GitHub Pages instead
  # push:
  #   branches: [ main ]
  # workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: false  # Disabled - using GitHub Pages for client-side app instead
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT || 22 }}
        script: |
          # Colors for output
          RED='\033[0;31m'
          GREEN='\033[0;32m'
          YELLOW='\033[1;33m'
          NC='\033[0m'
          
          echo -e "${GREEN}🚀 Starting deployment on $(hostname)...${NC}"
          
          # Navigate to project directory
          cd /home/${{ secrets.EC2_USER }}/monadage || {
            echo -e "${RED}Error: Project directory not found${NC}"
            exit 1
          }
          
          # Pull latest changes
          echo -e "${YELLOW}Pulling latest changes...${NC}"
          git pull origin main
          
          # Enter nix environment and deploy
          echo -e "${YELLOW}Entering nix environment and deploying...${NC}"
          nix develop --command ./deploy.sh
          
          # Health check
          echo -e "${YELLOW}Performing health check...${NC}"
          sleep 5
          if curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:5000/" | grep -q "200"; then
            echo -e "${GREEN}✅ Deployment successful - Application is responding${NC}"
          else
            echo -e "${RED}❌ Deployment failed - Application is not responding${NC}"
            exit 1
          fi
          
          echo -e "${GREEN}🎉 Deployment completed successfully!${NC}"